name: CI - Validacion Infraestructura ASIR

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  validacion-infraestructura:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Validar sintaxis Docker Compose
        run: docker-compose config
        
      - name: Aviso de éxito
        run: echo "¡La configuración de Docker es correcta! El pipeline ha pasado."
